# Используем официальный образ Python
FROM python:3.11-slim

# Устанавливаем зависимости
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем бота
COPY . .

# Запускаем бота
CMD ["python", "forex_signal_bot.py"]
